from selection_atlas.setup import AtlasSetup


# Initialise the atlas setup.
setup = AtlasSetup(
    atlas_id=config["atlas_id"],
    analysis_version=config["analysis_version"],
    cohorts_analysis=config["cohorts_analysis"],
    contigs=config["contigs"],
    dask_scheduler=config["dask_scheduler"],
)


# Includes.
include: "../common/rules/common.smk"
include: "rules/gwss-functions.smk"
include: "rules/gwss-rules.smk"


# Main rule.
rule all:
    input:
        get_gwss_results,
