import pandas as pd
import malariagen_data
import yaml

# open configuration file
configfile: "workflow/config.yaml"
chromosomes = config['ag']['contigs']

# include rule files
include: "rules/common.smk"
include: "rules/site.smk"
include: "rules/gwss.smk"

rule all:
    input:
        analyses = get_selection_atlas_outputs,
#        site = get_selection_atlas_site_pages,
