# Path to workflow config file.
from selection_atlas.setup import AtlasSetup


# Initialise the atlas setup.
setup = AtlasSetup(
    atlas_id=config["atlas_id"],
    analysis_version=config["analysis_version"],
    cohorts_analysis=config["cohorts_analysis"],
    contigs=config["contigs"],
    dask_scheduler=config["dask_scheduler"],
)


# Includes.
include: "../common/rules/common.smk"
include: "rules/site-functions.smk"
include: "rules/site-rules.smk"


# Main rule.
rule all:
    input:
        # This is the output directory from the Jupyter book compilation.
        setup.jb_build_dir,
