import pandas as pd
import geopandas as gpd
import yaml


configfile: "config/main.yaml"


include: "../rules/common-functions.py"
include: "../rules/common-rules.smk"
include: "rules/cohorts.smk"
include: "rules/gwss.smk"


rule all:
    input:
        analyses=get_analysis_results,
