import pandas as pd
import geopandas as gpd
import yaml


configfile: "config/main.yaml"


configpath = workflow.configfiles[0]
contigs = config["contigs"]
analysis_version = config["analysis_version"]
analysis_results_dir = f"results/{analysis_version}/analysis"


include: "rules/common.smk"
include: "rules/cohorts.smk"
include: "rules/gwss.smk"


rule all:
    input:
        analyses=get_analysis_results,
