# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Malaria vector selection atlas — <em>Anopheles gambiae</em> complex"
author: "Sanjay Nagi (<a href='https://github.com/sanjaynagi'>@sanjaynagi</a>) and Alistair Miles (<a href='https://github.com/alimanfoo/'>@alimanfoo</a>)."
copyright: "2025"
logo: logo.png

# Force re-execution of notebooks when the site is compiled.
# See https://jupyterbook.org/content/execute.html
execute:
    execute_notebooks: off

# Information about where the book exists on the web
repository:
    url: https://github.com/anopheles-genomic-surveillance.github.io/malaria-vector-selection-atlas # Online location of your book
    path_to_book: docs/ # Optional path to your book, relative to the repository root
    branch: main # Which branch of the repository should be used when creating links (optional)

sphinx:
    extra_extensions:
        - 'sphinx.ext.autodoc'
        - 'sphinx.ext.napoleon'
    config:
        myst_enable_extensions:
            - substitution
            - dollarmath
        html_js_files:
            - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
        suppress_warnings: ["mystnb.unknown_mime_type"]

# Define the name of the latex output file for PDF compilation.
latex:
    latex_documents:
        targetname: malaria-vector-selection-atlas-docs.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
    favicon : "favicon.ico"
    use_issues_button: true
    use_repository_button: true
    comments:
        utterances:
            repo: 'anopheles-genomic-surveillance/selection-atlas'
            issue-term: 'pathname'
            label: 'comment'
            theme: 'github-light'
