# Declare an identifier for this atlas. Will also be used as a URL slug.
atlas_id: "afun"

# Atlas title describing the taxon or taxonomic group covered.
atlas_title: "Malaria Vector Selection Atlas — *Anopheles funestus*"

# Set the analysis version identifier. This will be used to identify
# the outputs from a particular run of the analysis workflow. If you
# change any of the parameters in this configuration file then please
# also update the analysis version.
analysis_version: "2025.03.05"

# Set minimum and maximum cohort size parameters.
min_cohort_size: 15
max_cohort_size: 100  # If larger, will be randomly downsampled.

# Select the sample sets to include in the analysis.
sample_sets:
    - "1.0"

# Filter samples to include in the analysis.
sample_query: "taxon in ['funestus']"

# Declare which taxa to analyse.
taxa: ['funestus']

# Map taxa to phasing analysis.
taxon_phasing_analysis:
    funestus: "funestus"

# Map taxa to site mask.
taxon_site_mask:
    funestus: "funestus"

# Select the contigs to analyse.
contigs:
    - "2RL"
    - "3RL"
    - "X"

# Pin the cohorts analysis version in order to get reproducible results.
cohorts_analysis: "20240515"

# Window size calibration parameters.
h12_calibration_contig: "3RL"
h12_calibration_window_sizes: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1200, 1400, 1600, 1800, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 6000, 7000, 8000, 9000, 10000]
h12_calibration_threshold: 0.08
g123_calibration_contig: "3RL"
g123_calibration_window_sizes: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1200, 1400, 1600, 1800, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 6000, 7000, 8000, 9000, 10000]
g123_calibration_threshold: 0.08

# IHS configuration.
ihs_window_size: 100

# Configuration for H12 signal detection.
h12_signal_detection_min_delta_aic: 1000
h12_signal_detection_min_stat_max: 0.1
h12_signal_detection_gflanks: [6]

# Set this value to "single-threaded" when running snakemake with
# more than 1 CPU to avoid thrashing. Otherwise, both dask and
# snakemake will be trying to use multiple CPUs, and so CPU
# resources are likely to be oversubscribed.
dask_scheduler: "single-threaded"

# Insecticide resistance alerts.
ir_alerts:
    - 'SA-AFUN-01'
