# Declare an identifier for this atlas. Will also be used as a URL slug.
atlas_id: "agam"

# Atlas title describing the taxon or taxonomic group covered.
atlas_title: "CI"

# Set the analysis version identifier. This will be used to identify
# the outputs from a particular run of the analysis workflow. If you
# change any of the parameters in this configuration file then please
# also update the analysis version.
analysis_version: "CI"

# Set minimum and maximum cohort size parameters.
min_cohort_size: 20
max_cohort_size: 30

# Select the sample sets to include in the analysis.
sample_sets:
    - "AG1000G-ML-A"

# Filter samples to include in the analysis.
sample_query: "taxon in ['gambiae', 'coluzzii']"

# Declare which taxa to analyse.
taxa: ['gambiae', 'coluzzii']

# Map taxa to phasing analysis.
taxon_phasing_analysis:
    gambiae: "gamb_colu"
    coluzzii: "gamb_colu"
    bissau: "gamb_colu"
    arabiensis: "arab"

# Map taxa to site mask.
taxon_site_mask:
    gambiae: "gamb_colu"
    coluzzii: "gamb_colu"
    bissau: "gamb_colu"
    arabiensis: "arab"

# Select the contigs to analyse.
contigs:
    - "2R"

# Pin the cohorts analysis version in order to get reproducible results.
cohorts_analysis: "20240924"

# Window size calibration parameters.
h12_calibration_contig: "3L"
h12_calibration_window_sizes: [500, 1000, 2000, 5000]
h12_calibration_threshold: 0.08
g123_calibration_contig: "3L"
g123_calibration_window_sizes: [500, 1000, 2000, 5000]
g123_calibration_threshold: 0.08

# IHS configuration.
ihs_window_size: 100

# Configuration for H12 signal detection.
h12_signal_detection_min_delta_aic: 1000
h12_signal_detection_min_stat_max: 0.1
h12_signal_detection_gflanks: [6]

# Set this value to "single-threaded" when running snakemake with
# more than 1 CPU to avoid thrashing. Otherwise, both dask and
# snakemake will be trying to use multiple CPUs, and so CPU
# resources are likely to be oversubscribed.
dask_scheduler: "single-threaded"

# Insecticide resistance alerts.
ir_alerts:
    - 'CI'
