# Set the analysis version identifier. This will be used to identify
# the outputs from a particular run of the analysis workflow. If you
# change any of the parameters in this configuration file then please
# also update the analysis version.
analysis_version: "CI"

# Set minimum and maximum cohort size parameters.
min_cohort_size: 20  # TODO Could we live with 15 here?
max_cohort_size: 50  # TODO Maybe increase this for production?

# Select the sample sets to include in the analysis.
sample_sets:
    # - "3.0"
    # smaller dataset for development
    - "AG1000G-ML-A"

# Select the contigs to analyse.
contigs:
    - "2R"

# Pin the cohorts analysis version in order to get reproducible results.
cohorts_analysis: "20240924"

# Select the contig to use for H12 window size calibration.
h12_calibration_contig: "3L"
# Configuration for H12 signal detection.
h12_signal_detection_min_delta_aic: 1000
h12_signal_detection_min_stat_max: 0.1
h12_signal_detection_gflanks: [6]

# Set this value to "single-threaded" when running snakemake with
# more than 1 CPU to avoid thrashing. Otherwise, both dask and
# snakemake will be trying to use multiple CPUs, and so CPU
# resources are likely to be oversubscribed.
dask_scheduler: "single-threaded"

alerts:  ['CI']
